name: Publish release to Maven Central
on:
  workflow_dispatch:

jobs:
  publish-release:
    name: Publish release to Maven Central
    uses: entur/gha-maven-central/.github/workflows/gradle-publish.yml@main
    secrets: inherit
    with:
      next_version: ""
      push_to_repo: false
