name: Validate main
on:
  push:
    branches:
      - main

jobs:
  validate-gradle-build:
    uses: entur/abt-gha-public/.github/workflows/gradle-open-source-verify.yml@v1
    with:
      java-version: 21
